# Generated by Django 2.2 on 2019-04-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelime', '0002_auto_20190430_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kelimebilgi',
            old_name='Level',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='kelimebilgi',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='kelimebilgi',
            old_name='Word',
            new_name='word',
        ),
        migrations.RemoveField(
            model_name='kelimebilgi',
            name='Date',
        ),
        migrations.AddField(
            model_name='kelimebilgi',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sorulacak Tarih'),
        ),
    ]
