# Generated by Django 2.2 on 2019-05-11 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kelime', '0003_auto_20190430_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamamlananKelime',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True,null=True, verbose_name='Ezberleme Tarih')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,to='kelime.Kelime', verbose_name='Kelime')),
            ],
        ),
    ]
